on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: build and deploy to gcp
    steps:
    - id: install packages
      run: npm install 
    - id: build webpack 
      run: npm run build 
    - id: upload-files
      uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      with:
        credentials: ${{ secrets.gcp_credentials }}
        path: ./dist
        destination: garethgeorge-com
