on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: build and deploy to gcp
    steps:
    - id: checkout
      uses: actions/checkout@v2
    - id: install_packages
      run: npm install 
    - id: build_webpack 
      run: npm run build 
    - id: upload_files
      uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      with:
        credentials: ${{ secrets.gcp_credentials }}
        path: ./dist
        destination: garethgeorge-com
        gzip: true 
